# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-01 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=products.models.uplaod_image_path),
        ),
    ]
