# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-04-01 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210401_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=products.models.uplaod_image_path),
        ),
    ]
